version: "3.9"

services:
  redis:
    image: redis/redis-stack-server
    container_name: redis-stack-server
    restart: always
    network_mode: bridge
    expose:
      - 6379
  mongo:
    image: mongo
    container_name: mongo-server
    restart: always
    network_mode: bridge
    expose:
      - 27017

  teletalk-server:
    env_file:
      - ./environments/test_production_local.env
    build: .
    image: stalwart95/teletalk-server
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9000:9000
    links:
      - redis
      - mongo
