version: "3.9"

services:
  redis:
    image: redis
    container_name: redis-server
    restart: always
    network_mode: bridge
    expose:
      - 6379
  mongo:
    image: mongo
    container_name: mongo-server
    restart: always
    network_mode: bridge
    expose:
      - 27017

  teletalk-server:
    build: .
    image: stalwart95/teletalk-server
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8080:8080
    links:
      - redis
      - mongo
    # volumes:
    #   - .:/app
    #   - /app/node_modules
