@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}

POST {{baseUrl}}/user/register/normal/ HTTP/1.1
Content-Type: application/json

{
  "firstName":"ss",
  "lastName":"ss",
  "phoneNumber":"6012700470",
  "countryName":"iran",
  "countryCode":"11",
  "macAddress":"2200004189012",
  "username":"1233"
}