@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}


POST {{baseUrl}}/user/verify/signIn/normal HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiI5MDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwiaWF0IjoxNjM3ODU5MTcyfQ.9dsajdbMjXpWkiaySZr3hp81k3sCvPeaIZ497JvZs_w


### Main tokens =>
1012700470 : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiIxMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwicHJpdmF0ZUlEIjoiSVBablpKcmFQb0JkM09vcHhpRmhJN1lLd3hURjRDIiwiaWF0IjoxNjM3ODU5MTM2fQ.7u2hKnV8Su74m7R7C57XzcY5g_Lui7_fVRJLFF1lnFA 

9012700470 :  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiI5MDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwicHJpdmF0ZUlEIjoicE12czlWVGFWaXcwVVd3eTFsdDRGV2hQUXppRFV0IiwiaWF0IjoxNjM3ODU5MjIxfQ.RuFSXnD7Vab7ye8kFdbECAWI5pWvS5mHv94GDYZZTt0

6012700470 : 

### Verify token =>
1012700470 : 

9012700470 :  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiI5MDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwiaWF0IjoxNjM3ODU5MTcyfQ.9dsajdbMjXpWkiaySZr3hp81k3sCvPeaIZ497JvZs_w
