@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}


POST {{baseUrl}}/user/verify/signIn/normal HTTP/1.1
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiIxMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwiaWF0IjoxNjM3OTIzNjQ3fQ.DIwpqZItkI91v_lDDaLKs_zW3sXxaTjrfDN3rQQGuj4


### Main tokens =>
1012700470 : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiIxMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwicHJpdmF0ZUlEIjoic0hEZXBwVUZ4c3dKQi1wdDJ6RDJnazB4SlZ2enpQIiwiaWF0IjoxNjM3OTIzNjY2fQ.MKymwG1fZ5pmXuMkJns094oHpyKfvGYYi760_Is0ZJw


2012700470 : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiIyMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwicHJpdmF0ZUlEIjoickVvb3dYazVQZENtekRSTkRtY1JPUHlKQWdpUTU5IiwiaWF0IjoxNjM3OTIyODgyfQ.iYJuT5FbeNTxrlBSudYYpoklOjtgl6-kYmuWBgZcZ4I


6012700470 : 


9012700470 :  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiI5MDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwicHJpdmF0ZUlEIjoicE12czlWVGFWaXcwVVd3eTFsdDRGV2hQUXppRFV0IiwiaWF0IjoxNjM3ODU5MjIxfQ.RuFSXnD7Vab7ye8kFdbECAWI5pWvS5mHv94GDYZZTt0





### Verify token =>
1012700470 :  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiIxMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwiaWF0IjoxNjM3OTIzNjQ3fQ.DIwpqZItkI91v_lDDaLKs_zW3sXxaTjrfDN3rQQGuj4



2012700470 : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiIyMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwiaWF0IjoxNjM3OTE5MDY0fQ.T5Px2qruv7x0FOGjMzwDt8ej9rC6SZ-bzEYhJGegltk



9012700470 : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOnsicGhvbmVOdW1iZXIiOiI5MDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIifSwicHJpdmF0ZUlEIjoiNzBlXzVjajEwbWRJU0JPdDNualRyaERJckpUOFdoIiwiaWF0IjoxNjM3OTIyOTMyfQ.ElOVhnQ-2QT-jLKK5w6w2sVv3v_OPGkChWEvTGrTPBk
