@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}


POST {{baseUrl}}/cellphone/add/block/  HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOiIxMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIiLCJwYXNzIjoiNzg5MDA2IiwiaWF0IjoxNjM3MzE2Mjk0fQ.lDccbwf5TFrifNcaaO_ll0oqSplsDnQ7ytH1dwOK2yE

{
  "cellphone" : "6012700470",
  "countryCode": "98",
  "countryName": "ir"
}