POST {{$dotenv baseUrl}}/cellphone/add/block HTTP/1.1
content-type: application/json
Authorization: {{$dotenv user1}}

{
  "cellphone": {
    "countryCode": "98",
    "countryName": "ir",
    "phoneNumber" : "2012700470"
  } 
}