@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}


POST {{baseUrl}}/cellphone/add/contact  HTTP/1.1
content-type: application/json
Authorization: {{$dotenv user1}}

{
  "cellphone": {
    "countryCode": "98",
    "countryName": "ir",
    "phoneNumber" : "2012700470"
  },
  "firstName": "Soheil_SS74",
  "lastName": "SS"
}