@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}


POST {{baseUrl}}/cellphone/add/contact  HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOiI5MDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIiLCJwYXNzIjoiNjQ4Nzc5IiwiaWF0IjoxNjM3Njg0ODk1fQ.lvRRcm12ba1LOp_4UhTQk_f1d5dc9oKkLIZfaSeKFTA

{
  "cellphone": {
    "countryCode": "98",
    "countryName": "ir",
    "phoneNumber" : "1012700470"
  },
  "firstName": "Soheil_SS74",
  "lastName": "SS"
}