const environmentsKey = {
  JWT_MAIN_SECRET: "JWT_MAIN_SECRET",
  JWT_SIGN_IN_SECRET: "JWT_SIGN_IN_SECRET",
  LOCAL_PORT: "LOCAL_PORT",
  MONGO_URI_ATLAS: "MONGO_URI_ATLAS",
  MONGO_URI_LOCAL: "MONGO_URI_LOCAL",
  NODE_ENV: "NODE_ENV",
  PORT: "PORT",
  SMS_CLIENT_PASSWORD: "SMS_CLIENT_PASSWORD",
  SMS_CLIENT_USERNAME: "SMS_CLIENT_USERNAME",
};

module.exports = { environmentsKey };
