const CHAT_EXIST = {
	message: "chat is already initialized",
	reason: "CHAT_EXIST",
	version: "1.0.0",
};
const CHAT_ID_EXIST = {
	message: "",
	reason: "CHAT_ID_EXIST",
	version: "1.0.0",
};
const CHAT_ID_INVALID_TYPE = {
	message: "",
	reason: "CHAT_ID_INVALID_TYPE",
	version: "1.0.0",
};
const CHAT_ID_MAX_LENGTH_REACH = {
	message: "",
	reason: "CHAT_ID_MAX_LENGTH_REACH",
	version: "1.0.0",
};
const CHAT_ID_MIN_LENGTH_REACH = {
	message: "",
	reason: "CHAT_ID_MIN_LENGTH_REACH",
	version: "1.0.0",
};
const CHAT_ID_REQUIRED = {
	message: "",
	reason: "CHAT_ID_REQUIRED",
	version: "1.0.0",
};
const CHAT_NOT_EXIST = {
	message: "chat not exist, maybe deleted or something :)",
	reason: "CHAT_NOT_EXIST",
	version: "1.0.0",
};
const CREATED_AT_INVALID_TYPE = {
	message: "",
	reason: "CREATED_AT_INVALID_TYPE",
	version: "1.0.0",
};
const MESSAGE_ID_EXIST = {
	message: "",
	reason: "MESSAGE_ID_EXIST",
	version: "1.0.0",
};
const MESSAGE_ID_INVALID_TYPE = {
	message: "",
	reason: "MESSAGE_ID_INVALID_TYPE",
	version: "1.0.0",
};
const MESSAGE_ID_MAX_LENGTH_REACH = {
	message: "",
	reason: "MESSAGE_ID_MAX_LENGTH_REACH",
	version: "1.0.0",
};
const MESSAGE_ID_MIN_LENGTH_REACH = {
	message: "",
	reason: "MESSAGE_ID_MIN_LENGTH_REACH",
	version: "1.0.0",
};
const MESSAGE_ID_REQUIRED = {
	message: "",
	reason: "MESSAGE_ID_REQUIRED",
	version: "1.0.0",
};
const MESSAGE_TEXT_INVALID_TYPE = {
	message: "",
	reason: "MESSAGE_TEXT_INVALID_TYPE",
	version: "1.0.0",
};
const MESSAGE_TEXT_MAX_LENGTH_REACH = {
	message: "",
	reason: "MESSAGE_TEXT_MAX_LENGTH_REACH",
	version: "1.0.0",
};
const MESSAGE_TEXT_MIN_LENGTH_REACH = {
	message: "",
	reason: "MESSAGE_TEXT_MIN_LENGTH_REACH",
	version: "1.0.0",
};
const PARTICIPANT_ID_EXIST = {
	message: "",
	reason: "PARTICIPANT_ID_EXIST",
	version: "1.0.0",
};
const PARTICIPANT_ID_INVALID_TYPE = {
	message: "",
	reason: "PARTICIPANT_ID_INVALID_TYPE",
	version: "1.0.0",
};
const PARTICIPANT_ID_MAX_LENGTH_REACH = {
	message: "",
	reason: "PARTICIPANT_ID_MAX_LENGTH_REACH",
	version: "1.0.0",
};
const PARTICIPANT_ID_MIN_LENGTH_REACH = {
	message: "",
	reason: "PARTICIPANT_ID_MIN_LENGTH_REACH",
	version: "1.0.0",
};
const PARTICIPANT_ID_REQUIRED = {
	message: "",
	reason: "PARTICIPANT_ID_REQUIRED",
	version: "1.0.0",
};
const PARTICIPANT_NOT_EXIST = {
	message: "",
	reason: "PARTICIPANT_NOT_EXIST",
	version: "1.0.0",
};
const USER_NO_LONGER_PARTICIPANT = {
	message: "",
	reason: "USER_NO_LONGER_PARTICIPANT",
	version: "1.0.0",
};

const chatErrorTemplate = {
	version: "1.0.0",

	CHAT_EXIST,
	CHAT_ID_EXIST,
	CHAT_ID_INVALID_TYPE,
	CHAT_ID_MAX_LENGTH_REACH,
	CHAT_ID_MIN_LENGTH_REACH,
	CHAT_ID_REQUIRED,
	CHAT_NOT_EXIST,
	CREATED_AT_INVALID_TYPE,
	MESSAGE_ID_EXIST,
	MESSAGE_ID_INVALID_TYPE,
	MESSAGE_ID_MAX_LENGTH_REACH,
	MESSAGE_ID_MIN_LENGTH_REACH,
	MESSAGE_ID_REQUIRED,
	MESSAGE_TEXT_INVALID_TYPE,
	MESSAGE_TEXT_MAX_LENGTH_REACH,
	MESSAGE_TEXT_MIN_LENGTH_REACH,
	PARTICIPANT_ID_EXIST,
	PARTICIPANT_ID_INVALID_TYPE,
	PARTICIPANT_ID_MAX_LENGTH_REACH,
	PARTICIPANT_ID_MIN_LENGTH_REACH,
	PARTICIPANT_ID_REQUIRED,
	PARTICIPANT_NOT_EXIST,
	USER_NO_LONGER_PARTICIPANT,
};

module.exports = {
	chatErrorTemplate,

	CHAT_EXIST,
	CHAT_ID_EXIST,
	CHAT_ID_INVALID_TYPE,
	CHAT_ID_MAX_LENGTH_REACH,
	CHAT_ID_MIN_LENGTH_REACH,
	CHAT_ID_REQUIRED,
	CHAT_NOT_EXIST,
	CREATED_AT_INVALID_TYPE,
	MESSAGE_ID_EXIST,
	MESSAGE_ID_INVALID_TYPE,
	MESSAGE_ID_MAX_LENGTH_REACH,
	MESSAGE_ID_MIN_LENGTH_REACH,
	MESSAGE_ID_REQUIRED,
	MESSAGE_TEXT_INVALID_TYPE,
	MESSAGE_TEXT_MAX_LENGTH_REACH,
	MESSAGE_TEXT_MIN_LENGTH_REACH,
	PARTICIPANT_ID_EXIST,
	PARTICIPANT_ID_INVALID_TYPE,
	PARTICIPANT_ID_MAX_LENGTH_REACH,
	PARTICIPANT_ID_MIN_LENGTH_REACH,
	PARTICIPANT_ID_REQUIRED,
	PARTICIPANT_NOT_EXIST,
	USER_NO_LONGER_PARTICIPANT,
};
