const BIO_INVALID_TYPE = {
	message: "",
	reason: "BIO_INVALID_TYPE",
	version: "1.0.0",
};

const BIO_MAXLENGTH_REACH = {
	message: "",
	reason: "BIO_MAXLENGTH_REACH",
	version: "1.0.0",
};

const BIO_MINLENGTH_REACH = {
	message: "",
	reason: "BIO_MINLENGTH_REACH",
	version: "1.0.0",
};

const CELLPHONE_EXIST = {
	message: "",
	reason: "CELLPHONE_EXIST",
	version: "1.0.0",
};

const CELLPHONE_INVALID_TYPE = {
	message: "",
	reason: "CELLPHONE_INVALID_TYPE",
	version: "1.0.0",
};

const CELLPHONE_MAXLENGTH_REACH = {
	message: "",
	reason: "CELLPHONE_MAXLENGTH_REACH",
	version: "1.0.0",
};

const CELLPHONE_MINLENGTH_REACH = {
	message: "",
	reason: "CELLPHONE_MINLENGTH_REACH",
	version: "1.0.0",
};

const CELLPHONE_NOT_EXIST = {
	message: "",
	reason: "CELLPHONE_NOT_EXIST",
	version: "1.0.0",
};

const CELLPHONE_REQUIRED = {
	message: "",
	reason: "CELLPHONE_REQUIRED",
	version: "1.0.0",
};

const CELLPHONE_EXIST_IN_CONTACT = {
	message: "",
	reason: "CELLPHONE_EXIST_IN_CONTACT",
	version: "1.0.0",
};

const CONTACT_INVALID_TYPE = {
	message: "",
	reason: "CONTACT_INVALID_TYPE",
	version: "1.0.0",
};

const COUNTRY_CODE_INVALID_TYPE = {
	message: "",
	reason: "COUNTRY_CODE_INVALID_TYPE",
	version: "1.0.0",
};

const COUNTRY_CODE_MAXLENGTH_REACH = {
	message: "",
	reason: "COUNTRY_CODE_MAXLENGTH_REACH",
	version: "1.0.0",
};

const COUNTRY_CODE_MINLENGTH_REACH = {
	message: "",
	reason: "COUNTRY_CODE_MINLENGTH_REACH",
	version: "1.0.0",
};

const COUNTRY_CODE_REQUIRED = {
	message: "",
	reason: "COUNTRY_CODE_REQUIRED",
	version: "1.0.0",
};

const COUNTRY_NAME_INVALID_TYPE = {
	message: "",
	reason: "COUNTRY_NAME_INVALID_TYPE",
	version: "1.0.0",
};

const COUNTRY_NAME_MAXLENGTH_REACH = {
	message: "",
	reason: "COUNTRY_NAME_MAXLENGTH_REACH",
	version: "1.0.0",
};

const COUNTRY_NAME_MINLENGTH_REACH = {
	message: "",
	reason: "COUNTRY_NAME_MINLENGTH_REACH",
	version: "1.0.0",
};

const COUNTRY_NAME_REQUIRED = {
	message: "",
	reason: "COUNTRY_NAME_REQUIRED",
	version: "1.0.0",
};

const CREATED_AT_INVALID_TYPE = {
	message: "",
	reason: "CREATED_AT_INVALID_TYPE",
	version: "1.0.0",
};

const FIRST_NAME_INVALID_TYPE = {
	message: "",
	reason: "FIRST_NAME_INVALID_TYPE",
	version: "1.0.0",
};

const FIRST_NAME_MAXLENGTH_REACH = {
	message: "",
	reason: "FIRST_NAME_MAXLENGTH_REACH",
	version: "1.0.0",
};

const FIRST_NAME_MINLENGTH_REACH = {
	message: "",
	reason: "FIRST_NAME_MINLENGTH_REACH",
	version: "1.0.0",
};

const FIRST_NAME_REQUIRED = {
	message: "",
	reason: "FIRST_NAME_REQUIRED",
	version: "1.0.0",
};

const LAST_NAME_INVALID_TYPE = {
	message: "",
	reason: "LAST_NAME_INVALID_TYPE",
	version: "1.0.0",
};

const LAST_NAME_MAXLENGTH_REACH = {
	message: "",
	reason: "LAST_NAME_MAXLENGTH_REACH",
	version: "1.0.0",
};

const LAST_NAME_MINLENGTH_REACH = {
	message: "",
	reason: "LAST_NAME_MINLENGTH_REACH",
	version: "1.0.0",
};

const MAC_ADDRESS_EXIST = {
	message: "",
	reason: "MAC_ADDRESS_EXIST",
	version: "1.0.0",
};

const MAC_ADDRESS_INVALID_TYPE = {
	message: "",
	reason: "MAC_ADDRESS_INVALID_TYPE",
	version: "1.0.0",
};

const MAC_ADDRESS_MAXLENGTH_REACH = {
	message: "",
	reason: "MAC_ADDRESS_MAXLENGTH_REACH",
	version: "1.0.0",
};

const MAC_ADDRESS_MINLENGTH_REACH = {
	message: "",
	reason: "MAC_ADDRESS_MINLENGTH_REACH",
	version: "1.0.0",
};

const MAC_ADDRESS_REQUIRED = {
	message: "",
	reason: "MAC_ADDRESS_REQUIRED",
	version: "1.0.0",
};

const PHONE_NUMBER_INVALID_TYPE = {
	message: "",
	reason: "PHONE_NUMBER_INVALID_TYPE",
	version: "1.0.0",
};

const PHONE_NUMBER_EXIST = {
	message: "",
	reason: "PHONE_NUMBER_EXIST",
	version: "1.0.0",
};

const PHONE_NUMBER_REQUIRED = {
	message: "",
	reason: "PHONE_NUMBER_REQUIRED",
	version: "1.0.0",
};

const PHONE_NUMBER_MINLENGTH_REACH = {
	message: "",
	reason: "PHONE_NUMBER_MINLENGTH_REACH",
	version: "1.0.0",
};

const PHONE_NUMBER_MAXLENGTH_REACH = {
	message: "",
	reason: "PHONE_NUMBER_MAXLENGTH_REACH",
	version: "1.0.0",
};

const PRIVATE_ID_EXIST = {
	message: "",
	reason: "PRIVATE_ID_EXIST",
	version: "1.0.0",
};

const PRIVATE_ID_INVALID_TYPE = {
	message: "",
	reason: "PRIVATE_ID_INVALID_TYPE",
	version: "1.0.0",
};

const PRIVATE_ID_MAX_LENGTH_REACH = {
	message: "",
	reason: "PRIVATE_ID_MAX_LENGTH_REACH",
	version: "1.0.0",
};

const PRIVATE_ID_MIN_LENGTH_REACH = {
	message: "",
	reason: "PRIVATE_ID_MIN_LENGTH_REACH",
	version: "1.0.0",
};

const PRIVATE_ID_REQUIRED = {
	message: "",
	reason: "PRIVATE_ID_REQUIRED",
	version: "1.0.0",
};

const SELF_STUFF = {
	message: "",
	reason: "SELF_STUFF",
	version: "1.0.0",
};

const TOKEN_EXIST = {
	message: "",
	reason: "TOKEN_EXIST",
	version: "1.0.0",
};

const TOKEN_REQUIRED = {
	message: "",
	reason: "TOKEN_REQUIRED",
	version: "1.0.0",
};

const TOKEN_INVALID_TYPE = {
	message: "",
	reason: "TOKEN_INVALID_TYPE",
	version: "1.0.0",
};

const USER_NOT_EXIST = {
	message: "user not exist, maybe privateID is incorrect",
	reason: "USER_NOT_EXIST",
	version: "1.0.0",
};

const USERNAME_EXIST = {
	message: "",
	reason: "USERNAME_EXIST",
	version: "1.0.0",
};

const USERNAME_INVALID_TYPE = {
	message: "",
	reason: "USERNAME_INVALID_TYPE",
	version: "1.0.0",
};

const USERNAME_MAXLENGTH_REACH = {
	message: "",
	reason: "USERNAME_MAXLENGTH_REACH",
	version: "1.0.0",
};

const USERNAME_MINLENGTH_REACH = {
	message: "",
	reason: "USERNAME_MINLENGTH_REACH",
	version: "1.0.0",
};

const VERIFICATION_CODE_INVALID = {
	message: "Wrong verification code",
	reason: "VERIFICATION_CODE_INVALID",
	version: "1.0.0",
};

const VERIFICATION_CODE_INVALID_TYPE = {
	message: "",
	reason: "VERIFICATION_CODE_INVALID_TYPE",
	version: "1.0.0",
};

const VERIFICATION_CODE_INVALID_LENGTH = {
	message: "",
	reason: "VERIFICATION_CODE_INVALID_LENGTH",
	version: "1.0.0",
};

const userErrorTemplate = {
	version: "1.0.0",

	BIO_INVALID_TYPE,
	BIO_MAXLENGTH_REACH,
	BIO_MINLENGTH_REACH,
	CELLPHONE_EXIST,
	CELLPHONE_INVALID_TYPE,
	CELLPHONE_MAXLENGTH_REACH,
	CELLPHONE_MINLENGTH_REACH,
	CELLPHONE_NOT_EXIST,
	CELLPHONE_REQUIRED,
	CELLPHONE_EXIST_IN_CONTACT,
	CONTACT_INVALID_TYPE,
	COUNTRY_CODE_INVALID_TYPE,
	COUNTRY_CODE_MAXLENGTH_REACH,
	COUNTRY_CODE_MINLENGTH_REACH,
	COUNTRY_CODE_REQUIRED,
	COUNTRY_NAME_INVALID_TYPE,
	COUNTRY_NAME_MAXLENGTH_REACH,
	COUNTRY_NAME_MINLENGTH_REACH,
	COUNTRY_NAME_REQUIRED,
	CREATED_AT_INVALID_TYPE,
	FIRST_NAME_INVALID_TYPE,
	FIRST_NAME_MAXLENGTH_REACH,
	FIRST_NAME_MINLENGTH_REACH,
	FIRST_NAME_REQUIRED,
	LAST_NAME_INVALID_TYPE,
	LAST_NAME_MAXLENGTH_REACH,
	LAST_NAME_MINLENGTH_REACH,
	MAC_ADDRESS_EXIST,
	MAC_ADDRESS_INVALID_TYPE,
	MAC_ADDRESS_MAXLENGTH_REACH,
	MAC_ADDRESS_MINLENGTH_REACH,
	MAC_ADDRESS_REQUIRED,
	PHONE_NUMBER_INVALID_TYPE,
	PHONE_NUMBER_EXIST,
	PHONE_NUMBER_REQUIRED,
	PHONE_NUMBER_MINLENGTH_REACH,
	PHONE_NUMBER_MAXLENGTH_REACH,
	PRIVATE_ID_EXIST,
	PRIVATE_ID_INVALID_TYPE,
	PRIVATE_ID_MAX_LENGTH_REACH,
	PRIVATE_ID_MIN_LENGTH_REACH,
	PRIVATE_ID_REQUIRED,
	SELF_STUFF,
	TOKEN_EXIST,
	TOKEN_REQUIRED,
	TOKEN_INVALID_TYPE,
	USER_NOT_EXIST,
	USERNAME_EXIST,
	USERNAME_INVALID_TYPE,
	USERNAME_MAXLENGTH_REACH,
	USERNAME_MINLENGTH_REACH,
	VERIFICATION_CODE_INVALID,
	VERIFICATION_CODE_INVALID_TYPE,
	VERIFICATION_CODE_INVALID_LENGTH,
};

module.exports = {
	userErrorTemplate,

	BIO_INVALID_TYPE,
	BIO_MAXLENGTH_REACH,
	BIO_MINLENGTH_REACH,
	CELLPHONE_EXIST_IN_CONTACT,
	CELLPHONE_EXIST,
	CELLPHONE_INVALID_TYPE,
	CELLPHONE_MAXLENGTH_REACH,
	CELLPHONE_MINLENGTH_REACH,
	CELLPHONE_NOT_EXIST,
	CELLPHONE_REQUIRED,
	CONTACT_INVALID_TYPE,
	COUNTRY_CODE_INVALID_TYPE,
	COUNTRY_CODE_MAXLENGTH_REACH,
	COUNTRY_CODE_MINLENGTH_REACH,
	COUNTRY_CODE_REQUIRED,
	COUNTRY_NAME_INVALID_TYPE,
	COUNTRY_NAME_MAXLENGTH_REACH,
	COUNTRY_NAME_MINLENGTH_REACH,
	COUNTRY_NAME_REQUIRED,
	CREATED_AT_INVALID_TYPE,
	FIRST_NAME_INVALID_TYPE,
	FIRST_NAME_MAXLENGTH_REACH,
	FIRST_NAME_MINLENGTH_REACH,
	FIRST_NAME_REQUIRED,
	LAST_NAME_INVALID_TYPE,
	LAST_NAME_MAXLENGTH_REACH,
	LAST_NAME_MINLENGTH_REACH,
	MAC_ADDRESS_EXIST,
	MAC_ADDRESS_INVALID_TYPE,
	MAC_ADDRESS_MAXLENGTH_REACH,
	MAC_ADDRESS_MINLENGTH_REACH,
	MAC_ADDRESS_REQUIRED,
	PHONE_NUMBER_EXIST,
	PHONE_NUMBER_INVALID_TYPE,
	PHONE_NUMBER_MAXLENGTH_REACH,
	PHONE_NUMBER_MINLENGTH_REACH,
	PHONE_NUMBER_REQUIRED,
	PRIVATE_ID_EXIST,
	PRIVATE_ID_INVALID_TYPE,
	PRIVATE_ID_MAX_LENGTH_REACH,
	PRIVATE_ID_MIN_LENGTH_REACH,
	PRIVATE_ID_REQUIRED,
	SELF_STUFF,
	TOKEN_EXIST,
	TOKEN_INVALID_TYPE,
	TOKEN_REQUIRED,
	USER_NOT_EXIST,
	USERNAME_EXIST,
	USERNAME_INVALID_TYPE,
	USERNAME_MAXLENGTH_REACH,
	USERNAME_MINLENGTH_REACH,
	VERIFICATION_CODE_INVALID_LENGTH,
	VERIFICATION_CODE_INVALID_TYPE,
	VERIFICATION_CODE_INVALID,
};
