@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}


POST {{baseUrl}}/contact/add/  HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOiIxMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIiLCJwYXNzIjoiMzU2ODkwIiwiaWF0IjoxNjM3MDAyNDg3fQ.mLmrHmOGLiRloxtuOgqmRcxnG9jmlHqnZlL6SePjyjk


{
  "cellphone" : "9012700470",
  "countryCode": "98",
  "countryName": "ir"
}

###
90112700470



1012700470
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOiIxMDEyNzAwNDcwIiwiY291bnRyeUNvZGUiOiI5OCIsImNvdW50cnlOYW1lIjoiaXIiLCJwYXNzIjoiMzU2ODkwIiwiaWF0IjoxNjM3MDAyNDg3fQ.mLmrHmOGLiRloxtuOgqmRcxnG9jmlHqnZlL6SePjyjk