@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}


POST {{baseUrl}}/cellphone/add/contact  HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjZWxscGhvbmUiOiIwOTExMjM0NTY1NiIsImNvdW50cnlDb2RlIjoiOTgiLCJjb3VudHJ5TmFtZSI6ImlyIiwicGFzcyI6IjE2NjM1MyIsImlhdCI6MTYzNzYxNzU0Mn0.mOuWohVkuGemqtHA8Isk9xIvWA6mtmuT4w8aEf4Dz1c

{
  "cellphone" : "1234567890",
  "countryCode": "98",
  "countryName": "ir",
  "firstName": "Soheil_SS74",
  "lastName": "SS"
}