const {
	userError: {
		private_id_required,
		private_id_max_length_reach,
		private_id_min_length_reach,
		username_invalid_type,
		username_minlength_reach,
		username_maxlength_reach,
		first_name_required,
		first_name_minlength_reach,
		first_name_maxlength_reach,
		last_name_minlength_reach,
		last_name_maxlength_reach,
		cellphone_invalid_type,
		cellphone_required,
		cellphone_minlength_reach,
		cellphone_maxlength_reach,
		country_code_invalid_type,
		country_code_required,
		country_code_minlength_reach,
		country_code_maxlength_reach,
		country_name_invalid_type,
		country_name_required,
		country_name_minlength_reach,
		country_name_maxlength_reach,
		bio_minlength_reach,
		bio_maxlength_reach,
		mac_address_invalid_type,
		mac_address_required,
		mac_address_minlength_reach,
		mac_address_maxlength_reach,
	},
} = require("~/constant/error/schemaError/userSchemaError");

const { single } = require("teletalk-utils/index");

exports.userRegisterDefaultValue = {
	private_id: {
		type: "string",
		Type: String,
		unique: true,
		required: true,
		minlength: 30,
		maxlength: 35,
		trim: true,
		messages: {},
	},
	username: { type: "string", min: 3, trim: true, lowercase: true },
	first_name: {},
	last_name: {},
	cellphone: {},
	country_code: {},
	country_name: {},
	bio: {},
	mac_address: {},
	created_at: {},
};
