const userError = {
	private_id_invalid_type: "private_id_invalid_type",
	private_id_required: "private_id_required",
	private_id_exist: "private_id_exist",
	private_id_max_length_reach: "private_id_max_length_reach",
	private_id_min_length_reach: "private_id_min_length_reach",
	username_invalid_type: "username_invalid_type",
	username_exist: "username_exist",
	username_minlength_reach: "username_minlength_reach",
	username_maxlength_reach: "username_maxlength_reach",
	first_name_invalid_type: "first_name_invalid_type",
	first_name_required: "first_name_required",
	first_name_minlength_reach: "first_name_minlength_reach",
	first_name_maxlength_reach: "first_name_maxlength_reach",
	last_name_invalid_type: "last_name_invalid_type",
	last_name_minlength_reach: "last_name_minlength_reach",
	last_name_maxlength_reach: "last_name_maxlength_reach",
	cellphone_invalid_type: "cellphone_invalid_type",
	cellphone_required: "cellphone_required",
	cellphone_exist: "cellphone_exist",
	cellphone_minlength_reach: "cellphone_minlength_reach",
	cellphone_maxlength_reach: "cellphone_maxlength_reach",
	country_code_invalid_type: "country_code_invalid_type",
	country_code_required: "country_code_required",
	country_code_minlength_reach: "country_code_minlength_reach",
	country_code_maxlength_reach: "country_code_maxlength_reach",
	country_name_invalid_type: "country_name_invalid_type",
	country_name_required: "country_name_required",
	country_name_minlength_reach: "country_name_minlength_reach",
	country_name_maxlength_reach: "country_name_maxlength_reach",
	bio_invalid_type: "bio_invalid_type",
	bio_minlength_reach: "bio_minlength_reach",
	bio_maxlength_reach: "bio_maxlength_reach",
	mac_address_invalid_type: "mac_address_invalid_type",
	mac_address_required: "mac_address_required",
	mac_address_exist: "mac_address_exist",
	mac_address_minlength_reach: "mac_address_minlength_reach",
	mac_address_maxlength_reach: "mac_address_maxlength_reach",
	created_at_invalid_type: "created_at_invalid_type",
};

exports.userError = userError;
