import { errorBuilder } from "@/classes/ErrorBuilder";

import { ERROR_KEYS } from "@/variables/errors/errorKeys";
import { UNIQUE_ERROR_IDS } from "@/variables/errors/uniqueErrorIds";

const BIO_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BIO_EMPTY)
  .key(ERROR_KEYS.BIO_VALIDATION)
  .build();

const BIO_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BIO_INVALID)
  .key(ERROR_KEYS.BIO_VALIDATION)
  .build();

const BIO_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BIO_INVALID_TYPE)
  .key(ERROR_KEYS.BIO_VALIDATION)
  .build();

const BIO_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BIO_MAXLENGTH_REACH)
  .key(ERROR_KEYS.BIO_VALIDATION)
  .build();

const BIO_MINLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BIO_MINLENGTH_REACH)
  .key(ERROR_KEYS.BIO_VALIDATION)
  .build();

const BIO_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BIO_REQUIRED)
  .key(ERROR_KEYS.BIO_VALIDATION)
  .build();

const BLACKLIST_ITEM_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BLACKLIST_ITEM_EXIST)
  .key(ERROR_KEYS.BLACKLIST_VALIDATION)
  .build();

const BLACKLIST_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BLACKLIST_INVALID_TYPE)
  .key(ERROR_KEYS.BLACKLIST_VALIDATION)
  .build();

const BLACKLIST_ITEM_NOT_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BLACKLIST_ITEM_NOT_EXIST)
  .key(ERROR_KEYS.BLACKLIST_VALIDATION)
  .build();

const BLACKLIST_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.BLACKLIST_REQUIRED)
  .key(ERROR_KEYS.BLACKLIST_VALIDATION)
  .build();

const CELLPHONE_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CELLPHONE_EXIST)
  .key(ERROR_KEYS.CELLPHONE_VALIDATION)
  .build();

const CELLPHONE_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CELLPHONE_INVALID)
  .key(ERROR_KEYS.CELLPHONE_VALIDATION)
  .build();

const CELLPHONE_NOT_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CELLPHONE_NOT_EXIST)
  .key(ERROR_KEYS.CELLPHONE_VALIDATION)
  .build();

const CELLPHONE_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CELLPHONE_REQUIRED)
  .key(ERROR_KEYS.CELLPHONE_VALIDATION)
  .build();

const CELLPHONE_EXIST_IN_CONTACT = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CELLPHONE_EXIST_IN_CONTACT)
  .key(ERROR_KEYS.CELLPHONE_VALIDATION)
  .build();

const CHAT_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_EXIST)
  .key(ERROR_KEYS.CHAT_VALIDATION)
  .build();

const CHAT_NOT_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_NOT_EXIST)
  .key(ERROR_KEYS.CHAT_VALIDATION)
  .build();

const CHAT_ID_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_ID_EMPTY)
  .key(ERROR_KEYS.CHAT_ID_VALIDATION)
  .build();

const CHAT_ID_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_ID_EXIST)
  .key(ERROR_KEYS.CHAT_ID_VALIDATION)
  .build();

const CHAT_ID_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_ID_INVALID)
  .key(ERROR_KEYS.CHAT_ID_VALIDATION)
  .build();

const CHAT_ID_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_ID_INVALID_TYPE)
  .key(ERROR_KEYS.CHAT_ID_VALIDATION)
  .build();

const CHAT_ID_MAX_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_ID_MAX_LENGTH_REACH)
  .key(ERROR_KEYS.CHAT_ID_VALIDATION)
  .build();

const CHAT_ID_MIN_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_ID_MIN_LENGTH_REACH)
  .key(ERROR_KEYS.CHAT_ID_VALIDATION)
  .build();

const CHAT_ID_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHAT_ID_REQUIRED)
  .key(ERROR_KEYS.CHAT_ID_VALIDATION)
  .build();

const CHATS_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CHATS_INVALID_TYPE)
  .key(ERROR_KEYS.CHATS_VALIDATION)
  .build();

const CONTACT_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CONTACT_INVALID_TYPE)
  .key(ERROR_KEYS.CONTACT_VALIDATION)
  .build();

const CONTACTS_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CONTACTS_INVALID_TYPE)
  .key(ERROR_KEYS.CONTACT_VALIDATION)
  .build();

const CONTACTS_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CONTACTS_REQUIRED)
  .key(ERROR_KEYS.CONTACT_VALIDATION)
  .build();

const CONTACT_ITEM_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CONTACT_ITEM_EXIST)
  .key(ERROR_KEYS.CONTACT_VALIDATION)
  .build();

const CONTACT_ITEM_NOT_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CONTACT_ITEM_NOT_EXIST)
  .key(ERROR_KEYS.CONTACT_VALIDATION)
  .build();

const COUNTRY_CODE_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_CODE_INVALID_TYPE)
  .key(ERROR_KEYS.COUNTRY_CODE_VALIDATION)
  .build();

const COUNTRY_CODE_NUMERIC = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_CODE_NUMERIC)
  .key(ERROR_KEYS.COUNTRY_CODE_VALIDATION)
  .build();

const COUNTRY_CODE_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_CODE_INVALID)
  .key(ERROR_KEYS.COUNTRY_CODE_VALIDATION)
  .build();

const COUNTRY_CODE_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_CODE_EMPTY)
  .key(ERROR_KEYS.COUNTRY_CODE_VALIDATION)
  .build();

const COUNTRY_CODE_NOT_SUPPORTED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_CODE_NOT_SUPPORTED)
  .key(ERROR_KEYS.COUNTRY_CODE_VALIDATION)
  .build();

const COUNTRY_CODE_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_CODE_MAXLENGTH_REACH)
  .key(ERROR_KEYS.COUNTRY_CODE_VALIDATION)
  .build();

const COUNTRY_CODE_MINLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_CODE_MINLENGTH_REACH)
  .key(ERROR_KEYS.COUNTRY_CODE_VALIDATION)
  .build();

const COUNTRY_CODE_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_CODE_REQUIRED)
  .key(ERROR_KEYS.COUNTRY_CODE_VALIDATION)
  .build();

const COUNTRY_NOT_SUPPORTED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_NOT_SUPPORTED)
  .key(ERROR_KEYS.COUNTRY_NOT_SUPPORTED_VALIDATION)
  .build();

const CREATED_AT_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CREATED_AT_EMPTY)
  .key(ERROR_KEYS.CREATED_AT_VALIDATION)
  .build();

const COUNTRY_NAME_NOT_SUPPORTED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_NAME_NOT_SUPPORTED)
  .key(ERROR_KEYS.COUNTRY_NAME_VALIDATION)
  .build();

const COUNTRY_NAME_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_NAME_INVALID)
  .key(ERROR_KEYS.COUNTRY_NAME_VALIDATION)
  .build();

const COUNTRY_NAME_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_NAME_INVALID_TYPE)
  .key(ERROR_KEYS.COUNTRY_NAME_VALIDATION)
  .build();

const COUNTRY_NAME_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_NAME_EMPTY)
  .key(ERROR_KEYS.COUNTRY_NAME_VALIDATION)
  .build();

const COUNTRY_NAME_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_NAME_MAXLENGTH_REACH)
  .key(ERROR_KEYS.COUNTRY_NAME_VALIDATION)
  .build();

const COUNTRY_NAME_MINLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_NAME_MINLENGTH_REACH)
  .key(ERROR_KEYS.COUNTRY_NAME_VALIDATION)
  .build();

const COUNTRY_NAME_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.COUNTRY_NAME_REQUIRED)
  .key(ERROR_KEYS.COUNTRY_NAME_VALIDATION)
  .build();

const CREATED_AT_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CREATED_AT_INVALID_TYPE)
  .key(ERROR_KEYS.CREATED_AT_VALIDATION)
  .build();

const CREATED_AT_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.CREATED_AT_REQUIRED)
  .key(ERROR_KEYS.CREATED_AT_VALIDATION)
  .build();

const CURRENT_USER_EXIST = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.CURRENT_USER_EXIST)
  .key(ERROR_KEYS.USER_VALIDATION)
  .build();

const CURRENT_USER_NOT_EXIST = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.CURRENT_USER_NOT_EXIST)
  .key(ERROR_KEYS.USER_VALIDATION)
  .build();

const EVENT_NOT_FOUND = errorBuilder
  .create()
  .key(ERROR_KEYS.UNKNOWN_EVENT)
  .reason(UNIQUE_ERROR_IDS.EVENT_NOT_FOUND)
  .statusCode(404)
  .build();

const FIRST_NAME_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.FIRST_NAME_INVALID_TYPE)
  .key(ERROR_KEYS.FIRST_NAME_VALIDATION)
  .build();

const FIRST_NAME_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.FIRST_NAME_EMPTY)
  .key(ERROR_KEYS.FIRST_NAME_VALIDATION)
  .build();

const FIRST_NAME_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.FIRST_NAME_INVALID)
  .key(ERROR_KEYS.FIRST_NAME_VALIDATION)
  .build();

const FIRST_NAME_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.FIRST_NAME_MAXLENGTH_REACH)
  .key(ERROR_KEYS.FIRST_NAME_VALIDATION)
  .build();

const FIRST_NAME_MINLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.FIRST_NAME_MINLENGTH_REACH)
  .key(ERROR_KEYS.FIRST_NAME_VALIDATION)
  .build();

const FIRST_NAME_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.FIRST_NAME_REQUIRED)
  .key(ERROR_KEYS.FIRST_NAME_VALIDATION)
  .build();

const FULL_NAME_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.FULL_NAME_INVALID)
  .key(ERROR_KEYS.FULL_NAME_VALIDATION)
  .build();

const INPUT_FIELDS_MISSING = errorBuilder
  .create()
  .key(ERROR_KEYS.INPUT_OUTPUT_FIELDS)
  .reason(UNIQUE_ERROR_IDS.INPUT_FIELDS_MISSING)
  .build();

const INPUT_FIELDS_OVERLOAD = errorBuilder
  .create()
  .key(ERROR_KEYS.INPUT_OUTPUT_FIELDS)
  .reason(UNIQUE_ERROR_IDS.INPUT_FIELDS_OVERLOAD)
  .build();

const IS_NOT_A_CALLBACK = errorBuilder
  .create()
  .key(ERROR_KEYS.SOCKET_ARGS_VALIDATION)
  .reason(UNIQUE_ERROR_IDS.IS_NOT_A_CALLBACK)
  .build();

const INPUT_FIELD_INVALID_TYPE = errorBuilder
  .create()
  .key(ERROR_KEYS.INPUT_OUTPUT_FIELDS)
  .reason(UNIQUE_ERROR_IDS.INPUT_FIELD_INVALID_TYPE)
  .build();

const LAST_NAME_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.LAST_NAME_INVALID)
  .key(ERROR_KEYS.LAST_NAME_VALIDATION)
  .build();

const LAST_NAME_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.LAST_NAME_INVALID_TYPE)
  .key(ERROR_KEYS.LAST_NAME_VALIDATION)
  .build();

const LAST_NAME_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.LAST_NAME_EMPTY)
  .key(ERROR_KEYS.LAST_NAME_VALIDATION)
  .build();

const LAST_NAME_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.LAST_NAME_MAXLENGTH_REACH)
  .key(ERROR_KEYS.LAST_NAME_VALIDATION)
  .build();

const LAST_NAME_MINLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.LAST_NAME_MINLENGTH_REACH)
  .key(ERROR_KEYS.LAST_NAME_VALIDATION)
  .build();

const LAST_NAME_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.LAST_NAME_REQUIRED)
  .key(ERROR_KEYS.LAST_NAME_VALIDATION)
  .build();

const MAC_ADDRESS_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MAC_ADDRESS_EMPTY)
  .key(ERROR_KEYS.MAC_ADDRESS_VALIDATION)
  .build();

const MAC_ADDRESS_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MAC_ADDRESS_EXIST)
  .key(ERROR_KEYS.MAC_ADDRESS_VALIDATION)
  .build();

const MAC_ADDRESS_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MAC_ADDRESS_INVALID_TYPE)
  .key(ERROR_KEYS.MAC_ADDRESS_VALIDATION)
  .build();

const MAC_ADDRESS_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MAC_ADDRESS_MAXLENGTH_REACH)
  .key(ERROR_KEYS.MAC_ADDRESS_VALIDATION)
  .build();

const MAC_ADDRESS_MINLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MAC_ADDRESS_MINLENGTH_REACH)
  .key(ERROR_KEYS.MAC_ADDRESS_VALIDATION)
  .build();

const MAC_ADDRESS_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MAC_ADDRESS_REQUIRED)
  .key(ERROR_KEYS.MAC_ADDRESS_VALIDATION)
  .build();

const MESSAGE_ID_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_ID_EMPTY)
  .key(ERROR_KEYS.MESSAGE_ID_VALIDATION)
  .build();

const MESSAGE_ID_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_ID_EXIST)
  .key(ERROR_KEYS.MESSAGE_ID_VALIDATION)
  .build();

const MESSAGE_ID_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_ID_INVALID_TYPE)
  .key(ERROR_KEYS.MESSAGE_ID_VALIDATION)
  .build();

const MESSAGE_ID_MAX_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_ID_MAX_LENGTH_REACH)
  .key(ERROR_KEYS.MESSAGE_ID_VALIDATION)
  .build();

const MESSAGE_ID_MIN_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_ID_MIN_LENGTH_REACH)
  .key(ERROR_KEYS.MESSAGE_ID_VALIDATION)
  .build();

const MESSAGE_ID_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_ID_REQUIRED)
  .key(ERROR_KEYS.MESSAGE_ID_VALIDATION)
  .build();

const MESSAGE_TEXT_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_TEXT_INVALID_TYPE)
  .key(ERROR_KEYS.MESSAGE_TEXT_VALIDATION)
  .build();

const MESSAGE_TEXT_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_TEXT_EMPTY)
  .key(ERROR_KEYS.MESSAGE_TEXT_VALIDATION)
  .build();

const MESSAGE_TEXT_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_TEXT_INVALID)
  .key(ERROR_KEYS.MESSAGE_TEXT_VALIDATION)
  .build();

const MESSAGE_TEXT_MAX_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_TEXT_MAX_LENGTH_REACH)
  .key(ERROR_KEYS.MESSAGE_TEXT_VALIDATION)
  .build();

const MESSAGE_TEXT_MIN_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_TEXT_MIN_LENGTH_REACH)
  .key(ERROR_KEYS.MESSAGE_TEXT_VALIDATION)
  .build();

const MESSAGE_TEXT_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGE_TEXT_REQUIRED)
  .key(ERROR_KEYS.MESSAGE_TEXT_VALIDATION)
  .build();

const MESSAGES_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGES_INVALID_TYPE)
  .key(ERROR_KEYS.MESSAGES_VALIDATION)
  .build();

const MESSAGES_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.MESSAGES_REQUIRED)
  .key(ERROR_KEYS.MESSAGES_VALIDATION)
  .build();

const METHOD_NOT_ALLOWED = errorBuilder
  .create()
  .key(ERROR_KEYS.EXTERNAL_APP_ERROR)
  .reason(UNIQUE_ERROR_IDS.METHOD_NOT_ALLOWED)
  .statusCode(405)
  .build();

const ONLINE_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.ONLINE_INVALID_TYPE)
  .key(ERROR_KEYS.ONLINE_VALIDATION)
  .build();

const ONLINE_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.ONLINE_REQUIRED)
  .key(ERROR_KEYS.ONLINE_VALIDATION)
  .build();

const PHONE_NUMBER_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PHONE_NUMBER_INVALID_TYPE)
  .key(ERROR_KEYS.PHONE_NUMBER_VALIDATION)
  .build();

const PHONE_NUMBER_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PHONE_NUMBER_INVALID)
  .key(ERROR_KEYS.PHONE_NUMBER_VALIDATION)
  .build();

const PHONE_NUMBER_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PHONE_NUMBER_EMPTY)
  .key(ERROR_KEYS.PHONE_NUMBER_VALIDATION)
  .build();

const PHONE_NUMBER_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PHONE_NUMBER_EXIST)
  .key(ERROR_KEYS.PHONE_NUMBER_VALIDATION)
  .build();

const PHONE_NUMBER_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PHONE_NUMBER_REQUIRED)
  .key(ERROR_KEYS.PHONE_NUMBER_VALIDATION)
  .build();

const PRIVATE_CHATS_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PRIVATE_CHATS_INVALID_TYPE)
  .key(ERROR_KEYS.PRIVATE_CHAT_VALIDATION)
  .build();

const PHONE_NUMBER_MINLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PHONE_NUMBER_MINLENGTH_REACH)
  .key(ERROR_KEYS.PHONE_NUMBER_VALIDATION)
  .build();

const PHONE_NUMBER_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PHONE_NUMBER_MAXLENGTH_REACH)
  .key(ERROR_KEYS.PHONE_NUMBER_VALIDATION)
  .build();

const PHONE_NUMBER_NUMERIC = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PHONE_NUMBER_NUMERIC)
  .key(ERROR_KEYS.PHONE_NUMBER_VALIDATION)
  .build();

const SELF_STUFF = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SELF_STUFF)
  .key(ERROR_KEYS.SELF_STUFF_VALIDATION)
  .build();

const PARTICIPANT_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_EMPTY)
  .key(ERROR_KEYS.PARTICIPANT_VALIDATION)
  .build();

const PARTICIPANTS_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_EMPTY)
  .key(ERROR_KEYS.PARTICIPANTS_VALIDATION)
  .build();

const PARTICIPANTS_INVALID_LENGTH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANTS_INVALID_LENGTH)
  .key(ERROR_KEYS.PARTICIPANTS_VALIDATION)
  .build();

const PARTICIPANTS_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANTS_INVALID_TYPE)
  .key(ERROR_KEYS.PARTICIPANTS_VALIDATION)
  .build();

const PARTICIPANTS_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANTS_REQUIRED)
  .key(ERROR_KEYS.PARTICIPANTS_VALIDATION)
  .build();

const PARTICIPANT_ID_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_ID_EXIST)
  .key(ERROR_KEYS.PARTICIPANT_ID_VALIDATION)
  .build();

const PARTICIPANT_ID_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_ID_INVALID)
  .key(ERROR_KEYS.PARTICIPANT_ID_VALIDATION)
  .build();

const PARTICIPANT_ID_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_ID_INVALID_TYPE)
  .key(ERROR_KEYS.PARTICIPANT_ID_VALIDATION)
  .build();

const PARTICIPANT_ID_MAX_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_ID_MAX_LENGTH_REACH)
  .key(ERROR_KEYS.PARTICIPANT_ID_VALIDATION)
  .build();

const PARTICIPANT_ID_MIN_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_ID_MIN_LENGTH_REACH)
  .key(ERROR_KEYS.PARTICIPANT_ID_VALIDATION)
  .build();

const PARTICIPANT_ID_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_ID_REQUIRED)
  .key(ERROR_KEYS.PARTICIPANT_ID_VALIDATION)
  .build();

const PARTICIPANT_ID_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_ID_EMPTY)
  .key(ERROR_KEYS.PARTICIPANT_ID_VALIDATION)
  .build();

const PARTICIPANT_NOT_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.PARTICIPANT_NOT_EXIST)
  .key(ERROR_KEYS.PARTICIPANT_ID_VALIDATION)
  .build();

const ROUTE_NOT_FOUND = errorBuilder
  .create()
  .key(ERROR_KEYS.UNKNOWN_ROUTE)
  .reason(UNIQUE_ERROR_IDS.ROUTE_NOT_FOUND)
  .statusCode(404)
  .build();

const SENDER_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SENDER_EMPTY)
  .key(ERROR_KEYS.SENDER_ID_VALIDATION)
  .build();

const SENDER_ID_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SENDER_ID_EXIST)
  .key(ERROR_KEYS.SENDER_ID_VALIDATION)
  .build();

const SENDER_ID_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SENDER_ID_INVALID_TYPE)
  .key(ERROR_KEYS.SENDER_ID_VALIDATION)
  .build();

const SENDER_ID_MAX_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SENDER_ID_MAX_LENGTH_REACH)
  .key(ERROR_KEYS.SENDER_ID_VALIDATION)
  .build();

const SENDER_ID_MIN_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SENDER_ID_MIN_LENGTH_REACH)
  .key(ERROR_KEYS.SENDER_ID_VALIDATION)
  .build();

const SENDER_ID_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SENDER_ID_REQUIRED)
  .key(ERROR_KEYS.SENDER_ID_VALIDATION)
  .build();

const SESSIONS_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SESSIONS_INVALID_TYPE)
  .key(ERROR_KEYS.SESSIONS_VALIDATION)
  .build();

const SESSIONS_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.SESSIONS_REQUIRED)
  .key(ERROR_KEYS.SESSIONS_VALIDATION)
  .build();

const STATUS_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.STATUS_INVALID_TYPE)
  .key(ERROR_KEYS.STATUS_VALIDATION)
  .build();

const STATUS_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.STATUS_REQUIRED)
  .key(ERROR_KEYS.STATUS_VALIDATION)
  .build();

const TARGET_USER_NOT_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.TARGET_USER_NOT_EXIST)
  .key(ERROR_KEYS.TARGET_USER_VALIDATION)
  .build();

const TOKEN_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.TOKEN_EXIST)
  .key(ERROR_KEYS.TOKEN_VALIDATION)
  .build();

const TOKEN_REQUIRED = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TOKEN_REQUIRED)
  .key(ERROR_KEYS.TOKEN_VALIDATION)
  .build();

const TOKEN_INVALID = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TOKEN_INVALID)
  .key(ERROR_KEYS.TOKEN_VALIDATION)
  .build();

const TOKEN_EMPTY = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TOKEN_INVALID)
  .key(ERROR_KEYS.TOKEN_VALIDATION)
  .build();

const TOKEN_CAN_NOT_VERIFIED = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TOKEN_CAN_NOT_VERIFIED)
  .key(ERROR_KEYS.TOKEN_VALIDATION)
  .build();

const TOKEN_INVALID_TYPE = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TOKEN_INVALID_TYPE)
  .key(ERROR_KEYS.TOKEN_VALIDATION)
  .build();

const TOKEN_MINLENGTH_REACH = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TOKEN_MINLENGTH_REACH)
  .key(ERROR_KEYS.TOKEN_VALIDATION)
  .build();

const TOKEN_MAXLENGTH_REACH = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TOKEN_MAXLENGTH_REACH)
  .key(ERROR_KEYS.TOKEN_VALIDATION)
  .build();

const TEMPORARY_CLIENT_NOT_FOUND = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TEMPORARY_CLIENT_NOT_FOUND)
  .key(ERROR_KEYS.TEMPORARY_CLIENT_VALIDATION)
  .build();
const TEMPORARY_CLIENT_NOT_VERIFIED = errorBuilder
  .create()
  .statusCode(401)
  .reason(UNIQUE_ERROR_IDS.TEMPORARY_CLIENT_NOT_VERIFIED)
  .key(ERROR_KEYS.TEMPORARY_CLIENT_VALIDATION)
  .build();

const USER_NO_LONGER_PARTICIPANT = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_NO_LONGER_PARTICIPANT)
  .key(ERROR_KEYS.USER_VALIDATION)
  .build();

const USER_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_EXIST)
  .key(ERROR_KEYS.USER_VALIDATION)
  .build();

const USER_ID_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_ID_EXIST)
  .key(ERROR_KEYS.USER_ID_VALIDATION)
  .build();

const USER_ID_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_ID_INVALID_TYPE)
  .key(ERROR_KEYS.USER_ID_VALIDATION)
  .build();

const USER_ID_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_ID_INVALID)
  .key(ERROR_KEYS.USER_ID_VALIDATION)
  .build();

const USER_ID_MAX_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_ID_MAX_LENGTH_REACH)
  .key(ERROR_KEYS.USER_ID_VALIDATION)
  .build();

const USER_ID_MIN_LENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_ID_MIN_LENGTH_REACH)
  .key(ERROR_KEYS.USER_ID_VALIDATION)
  .build();

const USER_ID_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_ID_REQUIRED)
  .key(ERROR_KEYS.USER_ID_VALIDATION)
  .build();

const USER_ID_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USER_ID_EMPTY)
  .key(ERROR_KEYS.USER_ID_VALIDATION)
  .build();

const USERNAME_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USERNAME_EMPTY)
  .key(ERROR_KEYS.USERNAME_VALIDATION)
  .build();

const USERNAME_EXIST = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USERNAME_EXIST)
  .key(ERROR_KEYS.USERNAME_VALIDATION)
  .build();

const USERNAME_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USERNAME_INVALID_TYPE)
  .key(ERROR_KEYS.USERNAME_VALIDATION)
  .build();

const USERNAME_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USERNAME_INVALID)
  .key(ERROR_KEYS.USERNAME_VALIDATION)
  .build();

const USERNAME_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USERNAME_REQUIRED)
  .key(ERROR_KEYS.USERNAME_VALIDATION)
  .build();

const USERNAME_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USERNAME_MAXLENGTH_REACH)
  .key(ERROR_KEYS.USERNAME_VALIDATION)
  .build();

const USERNAME_MINLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.USERNAME_MINLENGTH_REACH)
  .key(ERROR_KEYS.USERNAME_VALIDATION)
  .build();

const VERIFICATION_CODE_INVALID = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.VERIFICATION_CODE_INVALID)
  .key(ERROR_KEYS.VERIFICATION_CODE_VALIDATION)
  .build();

const VERIFICATION_CODE_REQUIRED = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.VERIFICATION_CODE_REQUIRED)
  .key(ERROR_KEYS.VERIFICATION_CODE_VALIDATION)
  .build();

const VERIFICATION_CODE_INVALID_TYPE = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.VERIFICATION_CODE_INVALID_TYPE)
  .key(ERROR_KEYS.VERIFICATION_CODE_VALIDATION)
  .build();

const VERIFICATION_CODE_NUMERIC = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.VERIFICATION_CODE_NUMERIC)
  .key(ERROR_KEYS.VERIFICATION_CODE_VALIDATION)
  .build();

const VERIFICATION_CODE_EMPTY = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.VERIFICATION_CODE_EMPTY)
  .key(ERROR_KEYS.VERIFICATION_CODE_VALIDATION)
  .build();

const VERIFICATION_CODE_INVALID_LENGTH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.VERIFICATION_CODE_INVALID_LENGTH)
  .key(ERROR_KEYS.VERIFICATION_CODE_VALIDATION)
  .build();

const VERIFICATION_CODE_MAXLENGTH_REACH = errorBuilder
  .create()
  .reason(UNIQUE_ERROR_IDS.VERIFICATION_CODE_MAXLENGTH_REACH)
  .key(ERROR_KEYS.VERIFICATION_CODE_VALIDATION)
  .build();

const userErrors = {
  BIO_EMPTY,
  BIO_INVALID,
  BIO_INVALID_TYPE,
  BIO_MAXLENGTH_REACH,
  BIO_MINLENGTH_REACH,
  BIO_REQUIRED,
  BLACKLIST_INVALID_TYPE,
  BLACKLIST_ITEM_EXIST,
  BLACKLIST_ITEM_NOT_EXIST,
  BLACKLIST_REQUIRED,
  CELLPHONE_EXIST,
  CELLPHONE_EXIST_IN_CONTACT,
  CELLPHONE_INVALID,
  CELLPHONE_NOT_EXIST,
  CELLPHONE_REQUIRED,
  CHAT_EXIST,
  CHAT_ID_EMPTY,
  CHAT_ID_EXIST,
  CHAT_ID_INVALID,
  CHAT_ID_INVALID_TYPE,
  CHAT_ID_MAX_LENGTH_REACH,
  CHAT_ID_MIN_LENGTH_REACH,
  CHAT_ID_REQUIRED,
  CHAT_NOT_EXIST,
  CHATS_INVALID_TYPE,
  CONTACT_INVALID_TYPE,
  CONTACT_ITEM_EXIST,
  CONTACT_ITEM_NOT_EXIST,
  CONTACTS_INVALID_TYPE,
  CONTACTS_REQUIRED,
  COUNTRY_CODE_EMPTY,
  COUNTRY_CODE_INVALID,
  COUNTRY_CODE_INVALID_TYPE,
  COUNTRY_CODE_MAXLENGTH_REACH,
  COUNTRY_CODE_MINLENGTH_REACH,
  COUNTRY_CODE_NOT_SUPPORTED,
  COUNTRY_CODE_NUMERIC,
  COUNTRY_CODE_REQUIRED,
  COUNTRY_NAME_EMPTY,
  COUNTRY_NAME_INVALID,
  COUNTRY_NAME_INVALID_TYPE,
  COUNTRY_NAME_MAXLENGTH_REACH,
  COUNTRY_NAME_MINLENGTH_REACH,
  COUNTRY_NAME_NOT_SUPPORTED,
  COUNTRY_NAME_REQUIRED,
  COUNTRY_NOT_SUPPORTED,
  CREATED_AT_EMPTY,
  CREATED_AT_INVALID_TYPE,
  CREATED_AT_REQUIRED,
  CURRENT_USER_EXIST,
  CURRENT_USER_NOT_EXIST,
  EVENT_NOT_FOUND,
  FIRST_NAME_EMPTY,
  FIRST_NAME_INVALID,
  FIRST_NAME_INVALID_TYPE,
  FIRST_NAME_MAXLENGTH_REACH,
  FIRST_NAME_MINLENGTH_REACH,
  FIRST_NAME_REQUIRED,
  FULL_NAME_INVALID,
  INPUT_FIELD_INVALID_TYPE,
  INPUT_FIELDS_MISSING,
  INPUT_FIELDS_OVERLOAD,
  IS_NOT_A_CALLBACK,
  LAST_NAME_EMPTY,
  LAST_NAME_INVALID,
  LAST_NAME_INVALID_TYPE,
  LAST_NAME_MAXLENGTH_REACH,
  LAST_NAME_MINLENGTH_REACH,
  LAST_NAME_REQUIRED,
  MAC_ADDRESS_EMPTY,
  MAC_ADDRESS_EXIST,
  MAC_ADDRESS_INVALID_TYPE,
  MAC_ADDRESS_MAXLENGTH_REACH,
  MAC_ADDRESS_MINLENGTH_REACH,
  MAC_ADDRESS_REQUIRED,
  MESSAGE_ID_EMPTY,
  MESSAGE_ID_EXIST,
  MESSAGE_ID_INVALID_TYPE,
  MESSAGE_ID_MAX_LENGTH_REACH,
  MESSAGE_ID_MIN_LENGTH_REACH,
  MESSAGE_ID_REQUIRED,
  MESSAGE_TEXT_EMPTY,
  MESSAGE_TEXT_INVALID,
  MESSAGE_TEXT_INVALID_TYPE,
  MESSAGE_TEXT_MAX_LENGTH_REACH,
  MESSAGE_TEXT_MIN_LENGTH_REACH,
  MESSAGE_TEXT_REQUIRED,
  MESSAGES_INVALID_TYPE,
  MESSAGES_REQUIRED,
  METHOD_NOT_ALLOWED,
  ONLINE_INVALID_TYPE,
  ONLINE_REQUIRED,
  PARTICIPANT_EMPTY,
  PARTICIPANT_ID_EMPTY,
  PARTICIPANT_ID_EXIST,
  PARTICIPANT_ID_INVALID,
  PARTICIPANT_ID_INVALID_TYPE,
  PARTICIPANT_ID_MAX_LENGTH_REACH,
  PARTICIPANT_ID_MIN_LENGTH_REACH,
  PARTICIPANT_ID_REQUIRED,
  PARTICIPANT_NOT_EXIST,
  PARTICIPANTS_EMPTY,
  PARTICIPANTS_INVALID_LENGTH,
  PARTICIPANTS_INVALID_TYPE,
  PARTICIPANTS_REQUIRED,
  PHONE_NUMBER_EMPTY,
  PHONE_NUMBER_EXIST,
  PHONE_NUMBER_INVALID,
  PHONE_NUMBER_INVALID_TYPE,
  PHONE_NUMBER_MAXLENGTH_REACH,
  PHONE_NUMBER_MINLENGTH_REACH,
  PHONE_NUMBER_NUMERIC,
  PHONE_NUMBER_REQUIRED,
  PRIVATE_CHATS_INVALID_TYPE,
  ROUTE_NOT_FOUND,
  SELF_STUFF,
  SENDER_EMPTY,
  SENDER_ID_EXIST,
  SENDER_ID_INVALID_TYPE,
  SENDER_ID_MAX_LENGTH_REACH,
  SENDER_ID_MIN_LENGTH_REACH,
  SENDER_ID_REQUIRED,
  SESSIONS_INVALID_TYPE,
  SESSIONS_REQUIRED,
  STATUS_INVALID_TYPE,
  STATUS_REQUIRED,
  TARGET_USER_NOT_EXIST,
  TEMPORARY_CLIENT_NOT_FOUND,
  TEMPORARY_CLIENT_NOT_VERIFIED,
  TOKEN_CAN_NOT_VERIFIED,
  TOKEN_EMPTY,
  TOKEN_EXIST,
  TOKEN_INVALID,
  TOKEN_INVALID_TYPE,
  TOKEN_MAXLENGTH_REACH,
  TOKEN_MINLENGTH_REACH,
  TOKEN_REQUIRED,
  USER_EXIST,
  USER_ID_EMPTY,
  USER_ID_EXIST,
  USER_ID_INVALID,
  USER_ID_INVALID_TYPE,
  USER_ID_MAX_LENGTH_REACH,
  USER_ID_MIN_LENGTH_REACH,
  USER_ID_REQUIRED,
  USER_NO_LONGER_PARTICIPANT,
  USERNAME_EMPTY,
  USERNAME_EXIST,
  USERNAME_INVALID,
  USERNAME_INVALID_TYPE,
  USERNAME_MAXLENGTH_REACH,
  USERNAME_MINLENGTH_REACH,
  USERNAME_REQUIRED,
  VERIFICATION_CODE_EMPTY,
  VERIFICATION_CODE_INVALID,
  VERIFICATION_CODE_INVALID_LENGTH,
  VERIFICATION_CODE_INVALID_TYPE,
  VERIFICATION_CODE_MAXLENGTH_REACH,
  VERIFICATION_CODE_NUMERIC,
  VERIFICATION_CODE_REQUIRED,
};

export { userErrors };
