#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run test:dev:generate-badge && git add testSrc/passedTests.svg && npm run test:coverage && npx lint-staged

#  npm run build && npm run test:production:local &&
