const errorGeneratorInitialProperties = {
  code: 0,
  errorKey: "",
  message: "",
  reason: "",
  version: "",
};

const modelGeneratorInitialProperties = {
  value: null,
  error: errorGeneratorInitialProperties,
};

const initialValidatorPropValues = {
  type: {
    key: "type",
    values: {
      array: "array",
      arrayContains: "arrayContains",
      arrayEmpty: "arrayEmpty",
      arrayEnum: "arrayEnum",
      arrayLength: "arrayLength",
      arrayMax: "arrayMax",
      arrayMin: "arrayMin",
      arrayUnique: "arrayUnique",
      boolean: "boolean",
      date: "date",
      dateMax: "dateMax",
      dateMin: "dateMin",
      email: "email",
      emailEmpty: "emailEmpty",
      emailMax: "emailMax",
      emailMin: "emailMin",
      enumValue: "enumValue",
      equalField: "equalField",
      equalValue: "equalValue",
      forbidden: "forbidden",
      function: "function",
      luhn: "luhn",
      mac: "mac",
      number: "number",
      numberEqual: "numberEqual",
      numberInteger: "numberInteger",
      numberMax: "numberMax",
      numberMin: "numberMin",
      numberNegative: "numberNegative",
      numberNotEqual: "numberNotEqual",
      numberPositive: "numberPositive",
      object: "object",
      objectMaxProps: "objectMaxProps",
      objectMinProps: "objectMinProps",
      objectStrict: "objectStrict",
      string: "string",
      stringAlpha: "stringAlpha",
      stringAlphadash: "stringAlphadash",
      stringAlphanum: "stringAlphanum",
      stringBase64: "stringBase64",
      stringContains: "stringContains",
      stringEmpty: "stringEmpty",
      stringEnum: "stringEnum",
      stringHex: "stringHex",
      stringLength: "stringLength",
      stringMax: "stringMax",
      stringMin: "stringMin",
      stringNumeric: "stringNumeric",
      stringPattern: "stringPattern",
      stringSingleLine: "stringSingleLine",
      tuple: "tuple",
      tupleEmpty: "tupleEmpty",
      tupleLength: "tupleLength",
      url: "url",
      uuid: "uuid",
      uuidVersion: "uuidVersion",
    },
  },
};

const stateKeys = {
  temporaryClients: "temporaryClients",
  aliveClients: "aliveClients",
  users: "users",
  testUsers: "testUsers",
};

const inputOutputFields = {
  addedContact: "addedContact",
  bio: "bio",
  blacklist: "blacklist",
  blockedCellphone: "blockedCellphone",
  chatId: "newMessage",
  chats: "chats",
  contacts: "contacts",
  countryCode: "countryCode",
  countryName: "countryName",
  editedContact: "editedContact",
  firstName: "firstName",
  lastName: "lastName",
  macAddress: "macAddress",
  mainToken: "mainToken",
  message: "message",
  messageId: "messageId",
  messages: "messages",
  messageSender: "messageSender",
  newMessage: "newMessage",
  newUser: "newUser",
  participantId: "participantId",
  phoneNumber: "phoneNumber",
  privateId: "privateId",
  removedBlockedCellphone: "removedBlockedCellphone",
  removedContact: "removedContact",
  senderId: "senderId",
  user: "user",
  username: "username",
  verificationCode: "verificationCode",
  verifyToken: "verifyToken",
};

const initialValue = {
  modelGeneratorInitialProperties,
  errorGeneratorInitialProperties,
  initialValidatorPropValues,
  stateKeys,
};

module.exports = {
  initialValue,
  inputOutputFields,
};
