@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}

POST {{baseUrl}}/user/register/normal/ HTTP/1.1
Content-Type: application/json

{
  "first_name":"soheil",
  "last_name":"ss",
  "cellphone":"9012700470",
  "country_name":"iran",
  "country_code":"98"
  # "mac_address":"523456789012"
}