@url = http://localhost:
@port = 8080
@baseUrl = {{url}}{{port}}

POST {{baseUrl}}/user/register/normal/ HTTP/1.1
Content-Type: application/json

{
  "firstName":"soheil",
  "lastName":"ss",
  "cellphone":"9012700470",
  "countryName":"iran",
  "countryCode":"98"
  # "macAddress":"523456789012"
}