name: Build
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:

  build:
    env:
      CI: true

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x]
        operations: [ubuntu-latest]

    runs-on: ${{ matrix.operations }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Generate build
        run: npm run build
