name: Teletalk Server CI
on:
  push:
    branches: [teletalk-server-main]
  pull_request:
    branches: [teletalk-server-main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup/node@v2
        with:
          node-version: "16"
      - run: npm install
