name: CI
on:
  push:
    branches: [teletalk-server-main]
  pull_request:
    branches: [teletalk-server-main]

jobs:
  ci:
    env:
      CI: true

    strategy:
      matrix:
        mongodb-version: [4.4, 5.x, 6.x]
        node-version: [16.x, 18.x]
        operations: [ubuntu-latest]

    runs-on: ${{ matrix.operations }}

    steps:
      - uses: actions/checkout@v3

      - name: Install redis
        run: |
          chmod +x ./scripts/redisLoader.sh
          ./scripts/redisLoader.sh

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Start MongoDB version ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test development app
        run: npm run test:dev

      - name: Generate build
        run: npm run build

      - name: Test built app
        run: npm run test:production:local
