name: CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    env:
      CI: true

    strategy:
      fail-fast: false
      matrix:
        mongodb-version: [4.4, 5.0, 6.0]
        node-version: [16.x, 18.x]
        operations: [ubuntu-latest]

    runs-on: ${{ matrix.operations }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install redis
        run: |
          chmod +x ./scripts/redis-loader/portable.sh
          ./scripts/redis-loader/portable.sh

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Start MongoDB version ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test development app
        run: npm run test:dev
