name: CI
on:
  push:
    branches: [teletalk-server-main]
  pull_request:
    branches: [teletalk-server-main]

jobs:
  ci:
    env:
      CI: true

    strategy:
      matrix:
        mongodb-version: [4.4, 5.0, 6.0]
        node-version: [16.x, 18.x]
        operations: [ubuntu-latest]

    runs-on: ${{ matrix.operations }}

    container:
      image: node:18-alpine

    services:
      redis-stack-server:
        image: redis/redis-stack-server
        ports:
          - 6379/tcp
        # options: --entrypoint redis-stack

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Start MongoDB version ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test development app
        run: npm run test:dev
        env:
          REDIS_CLOUD_HOST: redis-stack-server
          REDIS_CLOUD_PORT: 6379

      - name: Generate build
        run: npm run build

      - name: Test built app
        run: npm run test:production:local
        env:
          REDIS_CLOUD_HOST: redis-stack-server
          REDIS_CLOUD_PORT: 6379
