name: Teletalk Server CI
on:
  push:
    branches: [teletalk-server-main]

  pull_request:
    branches: [teletalk-server-main]

jobs:
  build:
    env:
      CI: true
      LINTER_RULES_PATH: /
      JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
      VALIDATE_JAVASCRIPT_STANDARD: false

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        redis-version: [4, 5, 6]
        mongodb-version: [4.4, 5.0, 6.0]
        operations: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.operations }}

    steps:
      - uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter@v4

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install
      - run: npm run test
