name: CI
on:
  push:
    branches: [teletalk-server-main]
  pull_request:
    branches: [teletalk-server-main]

jobs:
  ci:
    env:
      CI: true

    strategy:
      matrix:
        mongodb-version: [4.4, 5.0, 6.0]
        node-version: [16.x, 18.x]
        operations: [ubuntu-latest]
        redis-version: [4, 5, 6]

    runs-on: ${{ matrix.operations }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Start Redis version ${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Start MongoDB version ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Test development app
        run: npm run test

      - name: Generate build app
        run: npm run build

      - name: Test production app
        run: npm run test-production