name: Code style
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  code_style:
    env:
      CI: true
      JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
      LINTER_RULES_PATH: /
      VALIDATE_JAVASCRIPT_STANDARD: false

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        operations: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.operations }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --only=development

      - name: Run prettier
        run: npm run check:format

      - name: Run eslint
        run: npm run check:lint
