name: Teletalk Server Coverage
on:
  push:
    branches: [teletalk-server-main]
  pull_request:
    branches: [teletalk-server-main]

jobs:
  build:
    env:
      CI: true

    strategy:
      matrix:
        mongodb-version: [6.0]
        node-version: [16.x]
        operations: [ubuntu-latest]
        redis-version: [6]

    runs-on: ${{ matrix.operations }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start Redis version ${{ matrix.redis-version }}
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Start MongoDB version ${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Generate coverage files
        run: npm run coverage

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3