name: Security with Snyk
on: push
jobs:
  security:
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - name: Snyk login
        run: snyk auth fc5f211a-84aa-47c8-a839-f96b24a3f0a5
      - name: Snyk monitor
        run: snyk test
      - name: Snyk monitor code
        run: snyk code test
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif